service: "api-deploy-ec2"

resources:
  Resources:
    EC2Instance:
      Type: AWS::EC2::Instance
      Properties:
        InstanceType: t2.micro
        ImageId: ami-01816d07b1128cd2d # Amazon Linux 2 AMI ID
        KeyName: aws-demo-ec2 # Key pair name
        SecurityGroupIds:
          - !Ref InstanceSecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y docker
            systemctl enable docker
            systemctl start docker
            docker pull agrajy10/api-deployment-ec2
            # Start the Docker container in detached mode
            # Map port 80 of the host (EC2 instance) to port 3000 of the container
            # This will allow us to access the web application by visiting the public IP of the EC2
            # instance on port 80
            docker run -d -p 80:3000 agrajy10/api-deployment-ec2

    InstanceSecurityGroup:
      Type: AWS::EC2::SecurityGroup
      Properties:
        GroupDescription: Enable HTTP and HTTPS access
        VpcId: vpc-0a52b02bb8ec4f2bd # Replace with your VPC ID
        SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 3000
            ToPort: 3000
            CidrIp: 0.0.0.0/0

  Outputs:
    InstancePublicIP:
      Description: Public IP of the newly created EC2 instance
      Value: !GetAtt EC2Instance.PublicIp
